"""add match team_creator_ids

Revision ID: 498568f45982
Revises: eda0b074d840
Create Date: 2026-08-23 02:30:37.232512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '498568f45982'
down_revision: Union[str, None] = 'eda0b074d840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: backfill existing rows ###
    op.add_column(
        'matches',
        sa.Column(
            'team_creator_ids',
            postgresql.ARRAY(sa.String(length=36)),
            nullable=False,
            server_default='{}',
        ),
    )
    op.alter_column('matches', 'team_creator_ids', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'team_creator_ids')
    # ### end Alembic commands ###
