"""initial schema

Revision ID: eda0b074d840
Revises: 
Create Date: 2026-08-23 01:06:03.468448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eda0b074d840'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_otps_phone'), 'user_otps', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_lowercase', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_img_url', sa.String(length=1024), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('player_role', sa.SmallInteger(), nullable=True),
    sa.Column('batting_style', sa.SmallInteger(), nullable=True),
    sa.Column('bowling_style', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name_lowercase'), 'users', ['name_lowercase'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('contact_support',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment_urls', postgresql.ARRAY(sa.String(length=1024)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_support_user_id'), 'contact_support', ['user_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('wickets', sa.Integer(), nullable=False),
    sa.Column('catches', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'field', 'user_id', name='uq_leaderboard_period_field_user')
    )
    op.create_index(op.f('ix_leaderboard_entries_field'), 'leaderboard_entries', ['field'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_period'), 'leaderboard_entries', ['period'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lowercase', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('name_initial', sa.String(length=8), nullable=True),
    sa.Column('profile_img_url', sa.String(length=1024), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name_lowercase'), 'teams', ['name_lowercase'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_img_url', sa.String(length=1024), nullable=True),
    sa.Column('banner_img_url', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_type', sa.SmallInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('device_fcm_token', sa.String(length=512), nullable=True),
    sa.Column('app_version', sa.Integer(), nullable=False),
    sa.Column('os_version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('batting', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bowling', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fielding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', name='uq_user_stats_user_type')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=True),
    sa.Column('match_group', sa.SmallInteger(), nullable=True),
    sa.Column('match_group_number', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.SmallInteger(), nullable=False),
    sa.Column('number_of_over', sa.Integer(), nullable=False),
    sa.Column('over_per_bowler', sa.Integer(), nullable=False),
    sa.Column('power_play_overs1', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('power_play_overs2', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('power_play_overs3', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('ground', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ball_type', sa.SmallInteger(), nullable=False),
    sa.Column('pitch_type', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('umpire_ids', postgresql.ARRAY(sa.String(length=36)), nullable=False),
    sa.Column('scorer_ids', postgresql.ARRAY(sa.String(length=36)), nullable=False),
    sa.Column('commentator_ids', postgresql.ARRAY(sa.String(length=36)), nullable=False),
    sa.Column('referee_id', sa.String(length=36), nullable=True),
    sa.Column('match_status', sa.SmallInteger(), nullable=False),
    sa.Column('toss_decision', sa.SmallInteger(), nullable=True),
    sa.Column('toss_winner_id', sa.String(length=36), nullable=True),
    sa.Column('current_playing_team_id', sa.String(length=36), nullable=True),
    sa.Column('revised_target', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_playing_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_created_by'), 'matches', ['created_by'], unique=False)
    op.create_index(op.f('ix_matches_match_status'), 'matches', ['match_status'], unique=False)
    op.create_index(op.f('ix_matches_start_at'), 'matches', ['start_at'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_table('team_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_players_team_user')
    )
    op.create_index(op.f('ix_team_players_team_id'), 'team_players', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_players_user_id'), 'team_players', ['user_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('tie', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('wickets', sa.Integer(), nullable=False),
    sa.Column('batting_average', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('bowling_average', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('highest_runs', sa.Integer(), nullable=False),
    sa.Column('lowest_runs', sa.Integer(), nullable=False),
    sa.Column('run_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('tournament_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_tournament_members_tournament_user')
    )
    op.create_index(op.f('ix_tournament_members_tournament_id'), 'tournament_members', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_tournament_members_user_id'), 'tournament_members', ['user_id'], unique=False)
    op.create_table('tournament_player_key_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_player_key_stats_player_id'), 'tournament_player_key_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_tournament_player_key_stats_tournament_id'), 'tournament_player_key_stats', ['tournament_id'], unique=False)
    op.create_table('tournament_team_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('nrr', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('played_matches', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_tournament_team_stats_tournament_team')
    )
    op.create_index(op.f('ix_tournament_team_stats_team_id'), 'tournament_team_stats', ['team_id'], unique=False)
    op.create_index(op.f('ix_tournament_team_stats_tournament_id'), 'tournament_team_stats', ['tournament_id'], unique=False)
    op.create_table('tournament_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_tournament_teams_tournament_team')
    )
    op.create_index(op.f('ix_tournament_teams_team_id'), 'tournament_teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_tournament_teams_tournament_id'), 'tournament_teams', ['tournament_id'], unique=False)
    op.create_table('innings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('overs', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_wickets', sa.Integer(), nullable=False),
    sa.Column('innings_status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_innings_match_id'), 'innings', ['match_id'], unique=False)
    op.create_table('match_settings',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('continue_with_injured_player', sa.Boolean(), nullable=False),
    sa.Column('show_wagon_wheel_for_less_run', sa.Boolean(), nullable=False),
    sa.Column('show_wagon_wheel_for_dot_ball', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('match_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('captain_id', sa.String(length=36), nullable=True),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('over', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('run', sa.Integer(), nullable=False),
    sa.Column('wicket', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_teams_match_team')
    )
    op.create_index(op.f('ix_match_teams_match_id'), 'match_teams', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_teams_team_id'), 'match_teams', ['team_id'], unique=False)
    op.create_table('ball_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inning_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.String(length=36), nullable=False),
    sa.Column('batsman_id', sa.String(length=36), nullable=False),
    sa.Column('non_striker_id', sa.String(length=36), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('extras_type', sa.SmallInteger(), nullable=True),
    sa.Column('extras_awarded', sa.Integer(), nullable=True),
    sa.Column('wicket_type', sa.SmallInteger(), nullable=True),
    sa.Column('fielding_position', sa.SmallInteger(), nullable=True),
    sa.Column('player_out_id', sa.String(length=36), nullable=True),
    sa.Column('wicket_taker_id', sa.String(length=36), nullable=True),
    sa.Column('is_four', sa.Boolean(), nullable=False),
    sa.Column('is_six', sa.Boolean(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batsman_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bowler_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inning_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['non_striker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_out_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wicket_taker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ball_scores_inning_id'), 'ball_scores', ['inning_id'], unique=False)
    op.create_index(op.f('ix_ball_scores_match_id'), 'ball_scores', ['match_id'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('inning_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bowler_id', sa.String(length=36), nullable=True),
    sa.Column('batsman_id', sa.String(length=36), nullable=True),
    sa.Column('fielding_position', sa.SmallInteger(), nullable=True),
    sa.Column('over', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ball_ids', postgresql.ARRAY(sa.String(length=36)), nullable=False),
    sa.Column('wickets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('milestone', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batsman_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bowler_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inning_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_inning_id'), 'match_events', ['inning_id'], unique=False)
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_table('match_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_team_id'], ['match_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_team_id', 'user_id', name='uq_match_players_team_user')
    )
    op.create_index(op.f('ix_match_players_match_team_id'), 'match_players', ['match_team_id'], unique=False)
    op.create_index(op.f('ix_match_players_user_id'), 'match_players', ['user_id'], unique=False)
    op.create_table('partnerships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('inning_id', sa.String(length=36), nullable=False),
    sa.Column('player_ids', postgresql.ARRAY(sa.String(length=36)), nullable=False),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('extras', sa.Integer(), nullable=False),
    sa.Column('ball_faced', sa.Integer(), nullable=False),
    sa.Column('start_over', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('end_over', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['inning_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partnerships_inning_id'), 'partnerships', ['inning_id'], unique=False)
    op.create_index(op.f('ix_partnerships_match_id'), 'partnerships', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partnerships_match_id'), table_name='partnerships')
    op.drop_index(op.f('ix_partnerships_inning_id'), table_name='partnerships')
    op.drop_table('partnerships')
    op.drop_index(op.f('ix_match_players_user_id'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_match_team_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_inning_id'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_ball_scores_match_id'), table_name='ball_scores')
    op.drop_index(op.f('ix_ball_scores_inning_id'), table_name='ball_scores')
    op.drop_table('ball_scores')
    op.drop_index(op.f('ix_match_teams_team_id'), table_name='match_teams')
    op.drop_index(op.f('ix_match_teams_match_id'), table_name='match_teams')
    op.drop_table('match_teams')
    op.drop_table('match_settings')
    op.drop_index(op.f('ix_innings_match_id'), table_name='innings')
    op.drop_table('innings')
    op.drop_index(op.f('ix_tournament_teams_tournament_id'), table_name='tournament_teams')
    op.drop_index(op.f('ix_tournament_teams_team_id'), table_name='tournament_teams')
    op.drop_table('tournament_teams')
    op.drop_index(op.f('ix_tournament_team_stats_tournament_id'), table_name='tournament_team_stats')
    op.drop_index(op.f('ix_tournament_team_stats_team_id'), table_name='tournament_team_stats')
    op.drop_table('tournament_team_stats')
    op.drop_index(op.f('ix_tournament_player_key_stats_tournament_id'), table_name='tournament_player_key_stats')
    op.drop_index(op.f('ix_tournament_player_key_stats_player_id'), table_name='tournament_player_key_stats')
    op.drop_table('tournament_player_key_stats')
    op.drop_index(op.f('ix_tournament_members_user_id'), table_name='tournament_members')
    op.drop_index(op.f('ix_tournament_members_tournament_id'), table_name='tournament_members')
    op.drop_table('tournament_members')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_team_players_user_id'), table_name='team_players')
    op.drop_index(op.f('ix_team_players_team_id'), table_name='team_players')
    op.drop_table('team_players')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_start_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_created_by'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_teams_name_lowercase'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_period'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_field'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_contact_support_user_id'), table_name='contact_support')
    op.drop_table('contact_support')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_name_lowercase'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_otps_phone'), table_name='user_otps')
    op.drop_table('user_otps')
    # ### end Alembic commands ###
